/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.BatchFluentHelperBasic;
import vdm.services.ZSCPMAXICONGUAGLIOSRVService;


/**
 * Default implementation of the {@link ZSCPMAXICONGUAGLIOSRVServiceBatch} interface exposed in the {@link vdm.services.ZSCPMAXICONGUAGLIOSRVService ZSCPMAXICONGUAGLIOSRVService}, allowing you to create multiple changesets and finally execute the batch request.
 * 
 */
public class DefaultZSCPMAXICONGUAGLIOSRVServiceBatch
    extends BatchFluentHelperBasic<ZSCPMAXICONGUAGLIOSRVServiceBatch, ZSCPMAXICONGUAGLIOSRVServiceBatchChangeSet>
    implements ZSCPMAXICONGUAGLIOSRVServiceBatch
{

    @Nonnull
    private final ZSCPMAXICONGUAGLIOSRVService service;

    /**
     * Creates a new instance of this DefaultZSCPMAXICONGUAGLIOSRVServiceBatch.
     * 
     * @param service
     *     The service to execute all operations in this changeset on.
     */
    public DefaultZSCPMAXICONGUAGLIOSRVServiceBatch(
        @Nonnull
        final ZSCPMAXICONGUAGLIOSRVService service) {
        this.service = service;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected String getServicePathForBatchRequest() {
        return ZSCPMAXICONGUAGLIOSRVService.DEFAULT_SERVICE_PATH;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected DefaultZSCPMAXICONGUAGLIOSRVServiceBatch getThis() {
        return this;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public ZSCPMAXICONGUAGLIOSRVServiceBatchChangeSet beginChangeSet() {
        return new DefaultZSCPMAXICONGUAGLIOSRVServiceBatchChangeSet(this, service);
    }

}
