/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv.batch;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.FluentHelperBatchEndChangeSet;


/**
 * This interface enables you to combine multiple operations into one change set. For further information have a look into the {@link vdm.services.ZSCPMAXICONGUAGLIOSRVService ZSCPMAXICONGUAGLIOSRVService}.
 * 
 */
public interface ZSCPMAXICONGUAGLIOSRVServiceBatchChangeSet
    extends FluentHelperBatchEndChangeSet<ZSCPMAXICONGUAGLIOSRVServiceBatch>
{


}
