/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv.batch;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.FluentHelperServiceBatch;


/**
 * Interface to the batch object of an {@code vdm.services.ZSCPMAXICONGUAGLIOSRVService ZSCPMAXICONGUAGLIOSRVService} service.
 * 
 */
public interface ZSCPMAXICONGUAGLIOSRVServiceBatch
    extends FluentHelperServiceBatch<ZSCPMAXICONGUAGLIOSRVServiceBatch, ZSCPMAXICONGUAGLIOSRVServiceBatchChangeSet>
{


}
