/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv01.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.BatchChangeSetFluentHelperBasic;
import vdm.services.ZSCPMAXICONGUAGLIOSRV01Service;


/**
 * Implementation of the {@link ZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet} interface, enabling you to combine multiple operations into one changeset. For further information have a look into the {@link vdm.services.ZSCPMAXICONGUAGLIOSRV01Service ZSCPMAXICONGUAGLIOSRV01Service}.
 * 
 */
public class DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet
    extends BatchChangeSetFluentHelperBasic<ZSCPMAXICONGUAGLIOSRV01ServiceBatch, ZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet>
    implements ZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet
{

    @Nonnull
    private final ZSCPMAXICONGUAGLIOSRV01Service service;

    DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet(
        @Nonnull
        final DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatch batchFluentHelper,
        @Nonnull
        final ZSCPMAXICONGUAGLIOSRV01Service service) {
        super(batchFluentHelper, batchFluentHelper);
        this.service = service;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet getThis() {
        return this;
    }

}
