/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv01.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.BatchFluentHelperBasic;
import vdm.services.ZSCPMAXICONGUAGLIOSRV01Service;


/**
 * Default implementation of the {@link ZSCPMAXICONGUAGLIOSRV01ServiceBatch} interface exposed in the {@link vdm.services.ZSCPMAXICONGUAGLIOSRV01Service ZSCPMAXICONGUAGLIOSRV01Service}, allowing you to create multiple changesets and finally execute the batch request.
 * 
 */
public class DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatch
    extends BatchFluentHelperBasic<ZSCPMAXICONGUAGLIOSRV01ServiceBatch, ZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet>
    implements ZSCPMAXICONGUAGLIOSRV01ServiceBatch
{

    @Nonnull
    private final ZSCPMAXICONGUAGLIOSRV01Service service;

    /**
     * Creates a new instance of this DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatch.
     * 
     * @param service
     *     The service to execute all operations in this changeset on.
     */
    public DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatch(
        @Nonnull
        final ZSCPMAXICONGUAGLIOSRV01Service service) {
        this.service = service;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected String getServicePathForBatchRequest() {
        return ZSCPMAXICONGUAGLIOSRV01Service.DEFAULT_SERVICE_PATH;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatch getThis() {
        return this;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public ZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet beginChangeSet() {
        return new DefaultZSCPMAXICONGUAGLIOSRV01ServiceBatchChangeSet(this, service);
    }

}
