/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD ZSCP_CHECK_VALUES_POD}. This interface is used by {@link vdm.namespaces.zscpmaxiconguagliosrv.field.ZSCP_CHECK_VALUES_PODField ZSCP_CHECK_VALUES_PODField} and {@link vdm.namespaces.zscpmaxiconguagliosrv.link.ZSCP_CHECK_VALUES_PODLink ZSCP_CHECK_VALUES_PODLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD#POD POD}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD#STATUS STATUS}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD#DESCRIZIONE DESCRIZIONE}</li>
 * </ul>
 * 
 */
public interface ZSCP_CHECK_VALUES_PODSelectable
    extends EntitySelectable<ZSCP_CHECK_VALUES_POD>
{


}
