/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES ZSCP_CHECK_VALUES}. This interface is used by {@link vdm.namespaces.zscpmaxiconguagliosrv.field.ZSCP_CHECK_VALUESField ZSCP_CHECK_VALUESField} and {@link vdm.namespaces.zscpmaxiconguagliosrv.link.ZSCP_CHECK_VALUESLink ZSCP_CHECK_VALUESLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES#POD POD}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES#TRADER TRADER}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES#AREA_TERRITORIALE AREA_TERRITORIALE}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES#STATUS STATUS}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES#DESCRIZIONE DESCRIZIONE}</li>
 * </ul>
 * 
 */
public interface ZSCP_CHECK_VALUESSelectable
    extends EntitySelectable<ZSCP_CHECK_VALUES>
{


}
