/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER ZSCP_CHECK_VALUES_TRADER}. This interface is used by {@link vdm.namespaces.zscpmaxiconguagliosrv.field.ZSCP_CHECK_VALUES_TRADERField ZSCP_CHECK_VALUES_TRADERField} and {@link vdm.namespaces.zscpmaxiconguagliosrv.link.ZSCP_CHECK_VALUES_TRADERLink ZSCP_CHECK_VALUES_TRADERLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER#TRADER TRADER}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER#STATUS STATUS}</li>
 * <li>{@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER#DESCRIZIONE DESCRIZIONE}</li>
 * </ul>
 * 
 */
public interface ZSCP_CHECK_VALUES_TRADERSelectable
    extends EntitySelectable<ZSCP_CHECK_VALUES_TRADER>
{


}
