/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpmaxiconguagliosrv;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.FluentHelperByKey;
import vdm.namespaces.zscpmaxiconguagliosrv.selectable.ZSCP_CHECK_VALUES_PODSelectable;


/**
 * Fluent helper to fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD ZSCP_CHECK_VALUES_POD} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class ZSCP_CHECK_VALUES_PODByKeyFluentHelper
    extends FluentHelperByKey<ZSCP_CHECK_VALUES_PODByKeyFluentHelper, ZSCP_CHECK_VALUES_POD, ZSCP_CHECK_VALUES_PODSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD ZSCP_CHECK_VALUES_POD} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param pod
     *     Def.punto cont.<p>Constraints: Not nullable, Maximum length: 50</p>
     * @param servicePath
     *     Service path to be used to fetch a single {@code ZSCP_CHECK_VALUES_POD}
     */
    public ZSCP_CHECK_VALUES_PODByKeyFluentHelper(
        @Nonnull
        final String servicePath, final String pod) {
        super(servicePath);
        this.key.put("Pod", pod);
    }

    @Override
    @Nonnull
    protected Class<ZSCP_CHECK_VALUES_POD> getEntityClass() {
        return ZSCP_CHECK_VALUES_POD.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
