/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.services;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.BatchService;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUESByKeyFluentHelper;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUESFluentHelper;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_PODByKeyFluentHelper;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_PODFluentHelper;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADERByKeyFluentHelper;
import vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADERFluentHelper;
import vdm.namespaces.zscpmaxiconguagliosrv.batch.ZSCPMAXICONGUAGLIOSRVServiceBatch;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>ZSCP_MAXI_CONGUAGLIO_SRV</td></tr></table>
 * 
 */
public interface ZSCPMAXICONGUAGLIOSRVService
    extends BatchService<ZSCPMAXICONGUAGLIOSRVServiceBatch>
{

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "/sap/opu/odata/sap/ZSCP_MAXI_CONGUAGLIO_SRV";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    ZSCPMAXICONGUAGLIOSRVService withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Fetch multiple {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES ZSCP_CHECK_VALUES} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES ZSCP_CHECK_VALUES} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUESFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ZSCP_CHECK_VALUESFluentHelper getAllZSCP_CHECK_VALUES();

    /**
     * Fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES ZSCP_CHECK_VALUES} entity using key fields.
     * 
     * @param pod
     *     Def.punto cont.<p>Constraints: Not nullable, Maximum length: 50</p>
     * @param trader
     *     Forn. servizi<p>Constraints: Not nullable, Maximum length: 10</p>
     * @return
     *     A fluent helper to fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES ZSCP_CHECK_VALUES} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUESByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ZSCP_CHECK_VALUESByKeyFluentHelper getZSCP_CHECK_VALUESByKey(final String pod, final String trader);

    /**
     * Fetch multiple {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD ZSCP_CHECK_VALUES_POD} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD ZSCP_CHECK_VALUES_POD} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_PODFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ZSCP_CHECK_VALUES_PODFluentHelper getAllZSCP_CHECK_VALUES_POD();

    /**
     * Fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD ZSCP_CHECK_VALUES_POD} entity using key fields.
     * 
     * @param pod
     *     Def.punto cont.<p>Constraints: Not nullable, Maximum length: 50</p>
     * @return
     *     A fluent helper to fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_POD ZSCP_CHECK_VALUES_POD} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_PODByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ZSCP_CHECK_VALUES_PODByKeyFluentHelper getZSCP_CHECK_VALUES_PODByKey(final String pod);

    /**
     * Fetch multiple {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER ZSCP_CHECK_VALUES_TRADER} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER ZSCP_CHECK_VALUES_TRADER} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADERFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ZSCP_CHECK_VALUES_TRADERFluentHelper getAllZSCP_CHECK_VALUES_TRADER();

    /**
     * Fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER ZSCP_CHECK_VALUES_TRADER} entity using key fields.
     * 
     * @param trader
     *     Forn. servizi<p>Constraints: Not nullable, Maximum length: 10</p>
     * @return
     *     A fluent helper to fetch a single {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADER ZSCP_CHECK_VALUES_TRADER} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link vdm.namespaces.zscpmaxiconguagliosrv.ZSCP_CHECK_VALUES_TRADERByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    ZSCP_CHECK_VALUES_TRADERByKeyFluentHelper getZSCP_CHECK_VALUES_TRADERByKey(final String trader);

}
